mode: rule
allow-lan: false
log-level: info
ipv6: true
find-process-mode: off
tcp-concurrent: true
unified-delay: true
disable-keep-alive: false
keep-alive-interval: 15
keep-alive-idle: 300
profile:
  store-selected: true
  store-fake-ip: true

###############################################################
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb

###############################################################
sniffer:
  enable: true
  # 对 redir-host 类型识别的流量进行强制嗅探
  force-dns-mapping: true
  # 对所有未获取到域名的流量进行强制嗅探
  parse-pure-ip: true
  # 是否使用嗅探结果作为实际访问，默认为 true
  override-destination: true
  sniff:
    QUIC:
      ports:
        - 443
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
  force-domain:
    - "+.netflix.com"
    - "+.nflxvideo.net"
    - "+.amazonaws.com"
    - "+.media.dssott.com"
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - "+.oray.com"
    - "+.sunlogin.net"
    - "+.push.apple.com"

###############################################################
dns:
  enable: true
  ipv6: true
  respect-rules: false
  cache-algorithm: arc
  use-hosts: false
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: rule
  fake-ip-filter:
    - DOMAIN-SUFFIX,localhost.work.weixin.qq.com,real-ip
    - DOMAIN-SUFFIX,parsec.app,real-ip
    - RULE-SET,direct_classical_no_resolve,real-ip
    - GEOSITE,private,real-ip
    - GEOSITE,connectivity-check,real-ip
    - GEOSITE,google-cn,real-ip
    - GEOSITE,apple,real-ip
    - GEOSITE,category-public-tracker,real-ip
    - GEOSITE,category-games,real-ip
    - GEOSITE,category-speedtest,real-ip
    - GEOSITE,microsoft,real-ip
    - GEOSITE,cn,real-ip
    - MATCH,fake-ip
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114
###############################################################

rule-providers:
  direct_classical_no_resolve:
    type: http
    url: https://raw.githubusercontent.com/weiguangchao/Clash/master/direct_classical_no_resolve.yaml
    interval: 86400
    behavior: classical
    format: yaml

rules:
  - RULE-SET,direct_classical_no_resolve,🎯 全球直连
  - GEOSITE,private,🎯 全球直连
  - GEOSITE,connectivity-check,🎯 全球直连
  - GEOSITE,google-cn,🎯 全球直连
  - GEOSITE,apple,🎯 全球直连
  - GEOSITE,category-public-tracker,🎯 全球直连
  - GEOSITE,category-games,🎯 全球直连
  - GEOSITE,bilibili,📺 Bilibili
  - GEOSITE,category-speedtest,⏱️ Speedtest
  - GEOSITE,github,🚀 节点选择
  - GEOSITE,microsoft,Ⓜ️ Microsoft
  - GEOSITE,youtube,📹 YouTube
  - GEOSITE,category-ai-!cn,🤖 AI
  - GEOSITE,cursor,🤖 AI
  - DOMAIN-SUFFIX,warp.dev,🤖 AI
  - GEOSITE,gfw,🚀 节点选择
  - GEOSITE,cn,🎯 全球直连
  - GEOIP,telegram,🚀 节点选择,no-resolve
  - GEOIP,private,🎯 全球直连,no-resolve
  - GEOIP,cn,🎯 全球直连,no-resolve
  - MATCH,🐟 漏网之鱼
