mode: rule
allow-lan: false
log-level: info
ipv6: false
find-process-mode: off
tcp-concurrent: true
unified-delay: true
disable-keep-alive: false
keep-alive-interval: 15
keep-alive-idle: 600
profile:
  store-selected: true
  store-fake-ip: true

###############################################################
geodata-mode: true
geodata-loader: memconservative
geo-auto-update: true
geo-update-interval: 24
geox-url:
  geoip: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat
  geosite: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
  mmdb: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb
  asn: https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb

###############################################################
sniffer:
  enable: true
  # 对 redir-host 类型识别的流量进行强制嗅探
  force-dns-mapping: true
  # 对所有未获取到域名的流量进行强制嗅探
  parse-pure-ip: true
  # 是否使用嗅探结果作为实际访问
  override-destination: false
  sniff:
    QUIC:
      ports:
        - 443
        - 8443
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080-8880
      override-destination: true
  force-domain:
    - +.netflix.com
    - +.nflxvideo.net
    - +.amazonaws.com
    - +.media.dssott.com
  skip-domain:
    - Mijia Cloud
    - dlg.io.mi.com
    - +.oray.com
    - +.sunlogin.net
    - +.push.apple.com
  skip-dst-address:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 127.0.0.0/8
    - 224.0.0.0/4

###############################################################
dns:
  enable: true
  ipv6: false
  respect-rules: false
  cache-algorithm: arc
  use-hosts: false
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - GEOSITE:private
    - GEOSITE:connectivity-check
    - +.localhost.work.weixin.qq.com
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114

rule-providers:
  direct_classical_no_resolve:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/weiguangchao/Clash/refs/heads/master/direct_classical_no_resolve.yaml
    interval: 86400

rules:
  #### Reject DROP ####
  - AND,((GEOSITE,category-ai-!cn),(NETWORK,UDP)),🛑 DROP
  - AND,((GEOSITE,cursor),(NETWORK,UDP)),🛑 DROP
  - AND,((GEOSITE,google),(NETWORK,UDP)),🛑 DROP
  #### Reject ####
  - GEOSITE,category-ads-all,🛑 REJECT
  #### Start ####
  - RULE-SET,direct_classical_no_resolve,🎯 全球直连
  - GEOSITE,private,🎯 全球直连
  - GEOSITE,connectivity-check,🎯 全球直连
  - GEOSITE,google-cn,🎯 全球直连
  - GEOSITE,category-public-tracker,🎯 全球直连
  - GEOSITE,category-cryptocurrency,🎯 全球直连
  - GEOSITE,apple,🍎 Apple
  - GEOSITE,category-games@cn,🎯 全球直连
  - GEOSITE,category-games,🎮 Game
  - GEOSITE,bilibili,📺 Bilibili
  - GEOSITE,category-speedtest,⏱️ Speedtest
  #### AI ####
  - GEOSITE,category-ai-!cn,🤖 AI
  - GEOSITE,cursor,🤖 AI
  #### Google ####
  - GEOSITE,youtube,📹 YouTube
  - GEOSITE,google,🇬 Google
  #### GitHub ####
  - GEOSITE,github,🚀 节点选择
  - GEOSITE,microsoft,Ⓜ️ Microsoft
  #### Final ####
  - GEOSITE,cn,🎯 全球直连
  - GEOIP,private,🎯 全球直连,no-resolve
  - GEOIP,cn,🎯 全球直连,no-resolve
  - MATCH,🐟 漏网之鱼
