mode: rule
allow-lan: false
log-level: info
ipv6: false
find-process-mode: off
tcp-concurrent: true
unified-delay: true
disable-keep-alive: false
keep-alive-interval: 15
keep-alive-idle: 300
profile:
  store-selected: true
  store-fake-ip: true

###############################################################
sniffer:
  enable: true
  # 对 redir-host 类型识别的流量进行强制嗅探
  force-dns-mapping: true
  # 对所有未获取到域名的流量进行强制嗅探
  parse-pure-ip: true
  # 是否使用嗅探结果作为实际访问
  override-destination: false
  sniff:
    QUIC:
      ports:
        - 443
        - 8443
    TLS:
      ports:
        - 443
        - 8443
    HTTP:
      ports:
        - 80
        - 8080-8880
  skip-domain:
    - Mijia Cloud
    - +.push.apple.com
  skip-dst-address:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 127.0.0.0/8
    - 224.0.0.0/4

###############################################################
dns:
  enable: true
  ipv6: false
  respect-rules: false
  cache-algorithm: arc
  use-hosts: false
  use-system-hosts: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "rule-set:fake-ip-filter"
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
    - 114.114.114.114

rule-providers:
  fake-ip-filter:
    type: http
    behavior: domain
    format: text
    url: https://raw.githubusercontent.com/weiguangchao/Clash/refs/heads/master/fake-ip-filter.list
    interval: 86400
  direct-classical-no-resolve:
    type: http
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/weiguangchao/Clash/refs/heads/master/direct-classical-no-resolve.yaml
    interval: 86400
  custom-direct-domain:
    type: http
    behavior: domain
    format: yaml
    url: https://api.asailor.org/Custom_OpenClash_Rules/main/rule/Custom_Direct_Domain.yaml
    interval: 86400
  # GEOSITE mrs 规则
  geosite-category-ads-all:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ads-all.mrs
    interval: 86400
  geosite-category-porn:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-porn.mrs
    interval: 86400
  geosite-category-ai-!cn:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-ai-!cn.mrs
    interval: 86400
  geosite-cursor:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cursor.mrs
    interval: 86400
  geosite-google:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.mrs
    interval: 86400
  geosite-google-cn:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google-cn.mrs
    interval: 86400
  geosite-private:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.mrs
    interval: 86400
  geosite-category-public-tracker:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-public-tracker.mrs
    interval: 86400
  geosite-apple:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple.mrs
    interval: 86400
  geosite-category-games@cn:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games@cn.mrs
    interval: 86400
  geosite-category-games:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.mrs
    interval: 86400
  geosite-bilibili:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/bilibili.mrs
    interval: 86400
  geosite-category-speedtest:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-speedtest.mrs
    interval: 86400
  geosite-youtube:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/youtube.mrs
    interval: 86400
  geosite-github:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/github.mrs
    interval: 86400
  geosite-microsoft:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/microsoft.mrs
    interval: 86400
  geosite-cn:
    type: http
    behavior: domain
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.mrs
    interval: 86400
  # GEOIP mrs 规则
  geoip-private:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.mrs
    interval: 86400
  geoip-telegram:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/telegram.mrs
    interval: 86400
  geoip-cn:
    type: http
    behavior: ipcidr
    format: mrs
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.mrs
    interval: 86400
rules:
  #### Reject ####
  - RULE-SET,geosite-category-ads-all,🛑 REJECT
  - RULE-SET,geosite-category-porn,🛑 REJECT
  #### Start ####
  - RULE-SET,direct-classical-no-resolve,🎯 全球直连
  - RULE-SET,custom-direct-domain,🎯 全球直连
  - RULE-SET,geosite-private,🎯 全球直连
  - RULE-SET,geosite-google-cn,🎯 全球直连
  - RULE-SET,geosite-category-public-tracker,🎯 全球直连
  - RULE-SET,geosite-apple,🍎 Apple
  - RULE-SET,geosite-category-games@cn,🎯 全球直连
  - RULE-SET,geosite-category-games,🎮 Game
  - RULE-SET,geosite-bilibili,📺 Bilibili
  - RULE-SET,geosite-category-speedtest,⏱️ Speedtest
  #### AI ####
  - AND,((RULE-SET,geosite-category-ai-!cn),(NETWORK,UDP)),🛑 DROP
  - AND,((RULE-SET,geosite-cursor),(NETWORK,UDP)),🛑 DROP
  - RULE-SET,geosite-category-ai-!cn,🤖 AI
  - RULE-SET,geosite-cursor,🤖 AI
  #### Google ####
  - AND,((RULE-SET,geosite-google),(NETWORK,UDP)),🛑 DROP
  - RULE-SET,geosite-youtube,📹 YouTube
  - RULE-SET,geosite-google,🇬 Google
  #### GitHub ####
  - RULE-SET,geosite-github,🚀 节点选择
  - RULE-SET,geosite-microsoft,Ⓜ️ Microsoft
  #### Final ####
  - RULE-SET,geoip-telegram,🚀 节点选择,no-resolve
  - RULE-SET,geosite-cn,🎯 全球直连
  - RULE-SET,geoip-private,🎯 全球直连,no-resolve
  - RULE-SET,geoip-cn,🎯 全球直连,no-resolve
  - MATCH,🐟 漏网之鱼
