[General]
bypass-system = true
dns-server = system
fallback-dns-server = system
ipv6 = true
prefer-ipv6 = false
private-ip-answer = true
skip-proxy = 192.168.0.0/16, 10.0.0.0/8, 172.16.0.0/12, localhost, *.local, captive.apple.com
tun-excluded-routes = 10.0.0.0/8, 100.64.0.0/10, 127.0.0.0/8, 169.254.0.0/16, 172.16.0.0/12, 192.0.0.0/24, 192.0.2.0/24, 192.88.99.0/24, 192.168.0.0/16, 198.51.100.0/24, 203.0.113.0/24, 224.0.0.0/4, 255.255.255.255/32, 239.255.255.250/32, ff02::fb/128
udp-policy-not-supported-behaviour = REJECT
update-url = https://raw.githubusercontent.com/weiguangchao/Clash/refs/heads/master/shadowrocket_whitelist.conf

[Rule]
IP-CIDR,152.175.28.50/32,DIRECT,no-resolve
IP-CIDR,5.5.5.5/32,DIRECT,no-resolve
IP-CIDR,211.173.70.32/32,DIRECT,no-resolve
IP-CIDR,179.253.242.5/32,DIRECT,no-resolve
IP-CIDR6,2605:52c0:2:5e40:be24:11ff:fe13:d24a/128,DIRECT,no-resolve
IP-CIDR6,2605:52c0:2:5e40:be24:11ff:fe2a:ee94/128,DIRECT,no-resolve
DOMAIN-SUFFIX,googleapis.cn,DIRECT
DOMAIN-SUFFIX,xn--ngstr-lra8j.com,DIRECT
DOMAIN-SUFFIX,compute.amazonaws.com,DIRECT
DOMAIN-SUFFIX,parsec.app,DIRECT
DOMAIN-SUFFIX,yiyone.work,DIRECT
DOMAIN-SUFFIX,yiyonex.com,DIRECT
DOMAIN-SUFFIX,yiyone.cc,DIRECT
DOMAIN-SUFFIX,yiy.one,DIRECT
DOMAIN-SUFFIX,mojie.cyou,DIRECT
DOMAIN-SUFFIX,mojcn.com,DIRECT
DOMAIN-SUFFIX,cnmjin.net,DIRECT
DOMAIN-SUFFIX,cnmjcn.cyou,DIRECT
DOMAIN-SUFFIX,mjanyt.com,DIRECT
DOMAIN-SUFFIX,mjhy2.com,DIRECT
DOMAIN-SUFFIX,linuxlh.xin,DIRECT
DOMAIN-SUFFIX,immersivetranslate.com,DIRECT
DOMAIN-SUFFIX,istatmenus.app,DIRECT
DOMAIN-SUFFIX,theluyuan.com,DIRECT
DOMAIN-SUFFIX,lightsoft.tech,DIRECT
DOMAIN-SUFFIX,nijigem.by,DIRECT
DOMAIN-SUFFIX,yunjnet.com,DIRECT
DOMAIN-SUFFIX,poke-mon.xyz,DIRECT
DOMAIN-SUFFIX,waimaosass.icu,DIRECT
DOMAIN-SUFFIX,gh-proxy.org,DIRECT
DOMAIN-SUFFIX,dynv6.net,DIRECT
DOMAIN-SUFFIX,dynv6.com,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Lan/Lan.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaMax/ChinaMax_Domain.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Apple/Apple_Domain.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/Microsoft/Microsoft.list,DIRECT
RULE-SET,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Shadowrocket/ChinaIPs/ChinaIPs.list,DIRECT
GEOIP,private,DIRECT,no-resolve
GEOIP,cn,DIRECT,no-resolve
FINAL,PROXY
